# Generated by Django 5.2.8 on 2025-11-30 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Swipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_like", models.BooleanField(verbose_name="Лайк?")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "swiped_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_swipes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кого свайпнули",
                    ),
                ),
                (
                    "swiper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_swipes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто свайпнул",
                    ),
                ),
            ],
            options={
                "verbose_name": "Свайп",
                "verbose_name_plural": "Свайпы",
                "unique_together": {("swiper", "swiped_user")},
            },
        ),
    ]
