# Generated by Django 5.2.8 on 2025-11-30 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Мужской"),
                            ("F", "Женский"),
                            ("O", "Другой/Не указан"),
                        ],
                        max_length=1,
                        verbose_name="Пол",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Дата рождения")),
                ("city", models.CharField(max_length=100)),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="О себе и увлечения"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("search", "В поиске"),
                            ("busy", "Занят(а)"),
                            ("married", "В браке"),
                            ("complicated", "Все сложно"),
                        ],
                        default="search",
                        max_length=20,
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=False, verbose_name="Приватный профиль"
                    ),
                ),
                ("likes_count", models.PositiveIntegerField(default=0)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Фотография профиля",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
